default_language_version:
  python: python
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: local
    hooks:
      - id: make-requirements
        name: "Make requirements.txt"
        entry: make
        language: system
        args: [ "requirements.txt" ]
