name: Tests
on:
  push:
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Dependencies
      run: |
        python -m pip install poetry
        poetry config virtualenvs.in-project true
        poetry install --without deploy
    - name: Make files
      run:  |
        make metropolis/local_rsa_privkey.pem
        make metropolis/local_settings.py
    - name: Migrations
      run: .venv/bin/python -Wa manage.py migrate
    - name: Django Tests
      run: .venv/bin/python -Wa manage.py test --parallel
