name: test
on: [ push ]
jobs:
  linter_name:
    name: runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Unit Tests
        run: |
          make metropolis/local_rsa_privkey.pem
          cat metropolis/local_rsa_privkey.pem
          make metropolis/local_settings.py
          python3 manage.py test
